project:
  type: website
  output-dir: _site

website:
  title: "InfernoCalibNet"
  repo-url: https://github.com/m4siko/InfernoCalibNet
  repo-actions: [issue, source]
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    contents:
      - section: "Overview"
        contents:
          - index.qmd
      - section: "Data preparations"
        contents:
        - 0.1-dataprep4CNNTrain.ipynb
        - 0.2-dataprep4InfernoTrain.ipynb
      - section: "CNN/Inferno evaluation"
        contents:
        - 1.1-thresholdUtility.ipynb
        - 1.2-clinicalUtilityR.ipynb
      - section: "Clinical Experiments"
        contents:
          - 2.1-clinicalExperiments.ipynb
          - 2.2-baseRateExperiment.ipynb
          - 2.3-calibrationCurves.ipynb
          - 2.4-mutualInformation.ipynb
      - section: "Full pipeline examples"
        contents:
        - 3.1-singeImageInspect.ipynb
        - 3.2-CNN2Inferno.ipynb
      - section: "Notes"
        contents:
          - 0.4-metrics.md
  navbar:
    right:
      - icon: github
        href: https://github.com/m4siko
      - icon: linkedin
        href: https://www.linkedin.com/in/maksim-ohvrill/
  page-footer:
    center: "© 2025 InfernoCalibNet - All Rights Reserved"

format:
  html:
    toc: true
    toc-location: right
    page-layout: full
    theme:
      light:
        - flatly
        - theme-light.scss
      dark:
        - darkly
        - theme-dark.scss
    mainfont: Palatino
