project:
  type: website
  output-dir: _site

website:
  title: "InfernoCalibNet"
  repo-url: https://github.com/m4siko/InfernoCalibNet
  repo-actions: [edit, source, issue]
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    contents:
      - section: "Overview"
        contents:
          - index.qmd
      - section: "Notebooks"
        contents:
          - 2.1-clinicalExperiments.ipynb
      - section: "Notes"
        contents:
          - 0.4-metrics.md
  navbar:
    right:
      - icon: github
        href: https://github.com/m4siko
      - icon: linkedin
        href: https://www.linkedin.com/in/maksim-ohvrill/
  page-footer:
    center: "© 2025 InfernoCalibNet - All Rights Reserved"

format:
  html:
    toc: true
    toc-location: right
    code-fold: true
    code-tools: true
    theme:
      light:
        - flatly
        - theme-light.scss
      dark:
        - darkly
        - theme-dark.scss
    mainfont: Palatino