project:
  type: website
  output-dir: _site

website:
  title: "My Documentation Site"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Notebooks
        menu:
          - text: Clinical Experiments
            file: 2.1-clinicalExperiments.ipynb
      - text: Notes
        menu:
          - text: Metrics
            file: 0.4-metrics.md
      - text: What's On
        file: whatson.qmd
      - text: Contributors
        file: contributors.qmd
    right:
      - icon: github
        href: https://github.com/m4siko
      - icon: linkedin
        href: https://linkedin.com/in/yourusername

format:
  html:
    toc: true
    toc-location: right
    theme:
      light: flatly
      dark: darkly
    mainfont: Palatino
