name: Deploy docsSite Quarto to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Copy notebooks, notes, and assets to docsSite
        run: |
          cp -r notebooks/* docsSite/ || true
          cp notes/0.4-metrics.md docsSite/ || true
          cp -r assets/* docsSite/ || true

      - name: Render the Quarto site
        run: quarto render
        working-directory: docsSite

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload built site
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docsSite/_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
